apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
  labels:
    app: opa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
      name: opa
    spec:
      containers:
        - name: opa
          image: ashutosh94/opa-server
          ports:
            - name: http
              containerPort: 8181
          livenessProbe:
            httpGet:
              scheme: HTTP # assumes OPA listens on localhost:8181
              port: 8181
            initialDelaySeconds: 5 # tune these periods for your environemnt
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health?bundle=true # Include bundle activation in readiness
              scheme: HTTP
              port: 8181
            initialDelaySeconds: 5
            periodSeconds: 5
---
kind: Service
apiVersion: v1
metadata:
  name: opa
  labels:
    app: opa
spec:
  type: NodePort
  selector:
    app: opa
  ports:
    - name: http
      protocol: TCP
      port: 8181
      targetPort: 8181
